# Generated by Django 3.1.7 on 2021-03-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=50, null='True', verbose_name='First name')),
                ('lastName', models.CharField(blank=True, max_length=50, null='True', verbose_name='Last name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank='True', max_length=20, null='True')),
                ('address', models.TextField(blank='True', null='True')),
                ('description', models.TextField(blank='True', null='True')),
                ('createAt', models.DateTimeField(verbose_name='Created at')),
            ],
        ),
    ]
